{% set name = "slang" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.jedsoft.org/releases/slang/slang-{{ version }}.tar.bz2
  sha256: f9145054ae131973c61208ea82486d5dd10e3c5cdad23b7c4a0617743c8f5a18

build:
  number: 0
  run_exports:
    # This package has been extremely stable
    # https://abi-laboratory.pro/index.php?view=timeline&l=slang
    - {{ pin_subpackage(name, max_pin='x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - gnuconfig  # [unix]
  host:
    - libiconv
    - libpng
    - oniguruma 6.9.*
    - pcre
    - readline
    - zlib
  run:
    - oniguruma 6.9.*

test:
  commands:
    - slsh --version  # [build_platform == target_platform]

about:
  home: http://www.jedsoft.org/slang
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: S-Lang allows developers to create robust multi-platform software

  description: |
    S-Lang is a multi-platform programmer's library designed to allow a
    developer to create robust multi-platform software. It provides facilities
    required by interactive applications such as display/screen management,
    keyboard input, keymaps, and so on. The most exciting feature of the library
    is the slang interpreter that may be easily embedded into a program to make
    it extensible. While the emphasis has always been on the embedded nature of
    the interpreter, it may also be used in a stand-alone fashion through the
    use of slsh, which is part of the S-Lang distribution.
  dev_url: git://git.jedsoft.org/git/slang.git
  doc_url: http://www.jedsoft.org/slang/docs.html

extra:
  recipe-maintainers:
    - sodre
    - matthiasdiener
