# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rOiL5EkEzMaqJUjTReNus/i3DgVIPpg26uNHgFnjYIiXTqyCRW+BH2PBbJS7CJw6LyIc0E2SxtRv4ptIso0vn4N/6FO8OirEX6ZD+WhfeVvBCaQmsgw4l2zvJ89ADZvY7k7jZ3wMhdp6SYPN949E/bpm6cnxFgGohaDaK2oQP36xSGTou3zqfI2LqzEf84EX/PuBaLQy0T/c0Z13HKn4X3Rkv8NIXme+pMNNan1Fe7bVPsep941cUxRAc0EMwuxv3S0Xnbc4f3KOx8tpRdPNEjQbWU5Jyx0rONrb5GV9R/RcLMRTH+QzWriqCgIf/QM0xlnCNd3AhEU6qNm6BVMlFbyL99Dldr/fIKUrO8OR8WLNwUcGHUBzISRCDDbxpZF8j3dWVaiCymV5d00P9jhDbDY7Z+03PhFn+uyM1z+Q5oYDXJf6bSntZvI+xHIQkLw1Haqe8CI8v+uGnftSnlL8Af5XWYFkbUKVVn+Q1+Q1PDA+pT25roNvmjMLuRBrNPJHl+aOilZcd5Gd0+QnchakDKJbf7UILIP6JLn/cfnKcyn6zZL4/Gu2Wsk17P4I4sKWgYmsXSDf8AGJpROWpELuzumiA/M5eeCd+Lz1iqU6lxwa1TkWktwe5C5oQJntKSGe8R5JuohEQnIHtucmGcelu86OLr7UwcM8FWM/NHRVJms="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml