appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rOiL5EkEzMaqJUjTReNus/i3DgVIPpg26uNHgFnjYIiXTqyCRW+BH2PBbJS7CJw6LyIc0E2SxtRv4ptIso0vn4N/6FO8OirEX6ZD+WhfeVvBCaQmsgw4l2zvJ89ADZvY7k7jZ3wMhdp6SYPN949E/bpm6cnxFgGohaDaK2oQP36xSGTou3zqfI2LqzEf84EX/PuBaLQy0T/c0Z13HKn4X3Rkv8NIXme+pMNNan1Fe7bVPsep941cUxRAc0EMwuxv3S0Xnbc4f3KOx8tpRdPNEjQbWU5Jyx0rONrb5GV9R/RcLMRTH+QzWriqCgIf/QM0xlnCNd3AhEU6qNm6BVMlFbyL99Dldr/fIKUrO8OR8WLNwUcGHUBzISRCDDbxpZF8j3dWVaiCymV5d00P9jhDbDY7Z+03PhFn+uyM1z+Q5oYDXJf6bSntZvI+xHIQkLw1Haqe8CI8v+uGnftSnlL8Af5XWYFkbUKVVn+Q1+Q1PDA+pT25roNvmjMLuRBrNPJHl+aOilZcd5Gd0+QnchakDKJbf7UILIP6JLn/cfnKcyn6zZL4/Gu2Wsk17P4I4sKWgYmsXSDf8AGJpROWpELuzumiA/M5eeCd+Lz1iqU6lxwa1TkWktwe5C5oQJntKSGe8R5JuohEQnIHtucmGcelu86OLr7UwcM8FWM/NHRVJms=}
